server:
  port: 9000
spring:
  application:
    name: hotel-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5 #每间隔5秒，从注册中心拉取一次最新的服务列表
  instance:
    lease-renewal-interval-in-seconds: 10 #每10秒钟，向注册中心发送一次心跳
    lease-expiration-duration-in-seconds: 30 #如果30秒未接收到心跳，剔除该服务
zuul:
  prefix: /api
  routes:
    item-service: /item/** #发出item开头的请求，就去访问：item-service